src/digitalmarket/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView
from products.views import UserLibraryListView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('test/', CheckoutTestView.as_view(), name='test'),
    path('checkout/', CheckoutAjaxView.as_view(), name='checkout'),
    path('admin/', admin.site.urls),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('seller/', include(('sellers.urls', 'sellers'), namespace='sellers')),
    path('tags/', include(('tags.urls', 'tags'), namespace='tags')),
    path('library/', UserLibraryListView.as_view(), name='library'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tags/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    TagDetailView,
    TagListView
)

urlpatterns = [
    path('', TagListView.as_view(), name="list"),
    path('<slug>/', TagDetailView.as_view(), name="detail"),

]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>

.main-content {
  width: 800px;
  margin: 0 auto;
  clear: both;
}

.main-nav {
    width: 800px;
    margin: 10px auto;
}

.main-nav li {
    display: inline;
}

.first-nav {
    padding-left: 0px;
}

.pull-right {
    float: right;
}

.pull-left {
    float: left;
}

.col-primary {
    width: 85%;
}

.col-sidebar {
    width: 15%;
}

.clearfix {
    clear:both;
}

#purchase-btn {
    color: red;
}

button.buy-btn {
	border: 1px solid #DA5B00 !important;
	background: #DA5B00 !important;
}

button.buy-btn .ui-button-text {
	color: #ffffff;
}

.ui-widget-header {
	border: 1px solid #ffffff !important;
	background: #ffffff !important;
}

{% block style %}{% endblock style %}
</style>
</head>

<body>

<nav class='main-nav'>

    <ul class ='pull-left first-nav'>
        <li><a href='{% url "dashboard" %}'>Digital Marketplace</a></li>
    </ul>
    <ul class ='pull-right'>
        <li><a href='{% url "products:list" %}'>Products</a></li>
        <li><a href='{% url "tags:list" %}'>Tags</a></li>
        <li><a href='{% url "library" %}'>Library</a></li>
    </ul>

</nav>

<div class="main-content">

{% block content %}

{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

<script src='{% static "js/django.csrf.js" %}'></script>

<script>
$(document).ready(function(){
    {% block jquery %}
    {% endblock jquery %}
})
</script>

</body>
</html>

src/templates/create_view.html
{% extends "base.html" %}

{% block content %}
{% include "form_include.html" with form=form submit_btn="Create Product" %}
{% endblock %}

src/templates/detail_view.html
{% extends "base.html" %}
{% block content %}

<h1>Product: {{  object.title }}</h1>
<p>{{ object.description }}</p>
<p>{{ object.price }}</p>

{{ block.super}}
{% endblock %}

src/templates/form.html
{% extends "base.html" %}

{% block content %}
{% include "form_include.html" with form=form submit_btn=submit_btn %}
{% endblock %}

src/templates/form_include.html
<form method="POST" action"" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='{% if submit_btn %} {{ submit_btn }} {% else %} Submit {% endif %}' />
</form>

src/templates/list_view.html
{% extends "base.html" %}
{% block style%}
h1 {
  color: green;
}
{% endblock %}
{% block content %}

<h1>List View</h1>

{{ queryset }}

{% endblock %}

src/templates/update_view.html
{% extends "base.html" %}

{% block content %}
{% include "form_include.html" with form=form submit_btn="Update Product" %}
{% endblock %}