src/digitalmarket/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView
from products.views import UserLibraryListView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('test/', CheckoutTestView.as_view(), name='test'),
    path('checkout/', CheckoutAjaxView.as_view(), name='checkout'),
    path('admin/', admin.site.urls),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('seller/', include(('sellers.urls', 'sellers'), namespace='sellers')),
    path('tags/', include(('tags.urls', 'tags'), namespace='tags')),
    path('library/', UserLibraryListView.as_view(), name='library'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

from .views import (
        ProductCreateView,
        ProductDetailView,
        ProductDownloadView,
        ProductListView,
        ProductUpdateView,
        ProductRatingAjaxView,
        VendorListView,
)

urlpatterns = [
    path('', ProductListView.as_view(), name="list"), #products:list
    path('vendor/', RedirectView.as_view(pattern_name='products:list'), name="vendor_list"),
    path('vendor/<vendor_name>/', VendorListView.as_view(), name="vendor_detail"),
    path('<int:pk>/', ProductDetailView.as_view(), name="detail"),
    path('<slug>/', ProductDetailView.as_view(), name="detail_slug"),
    path('<int:pk>/download/', ProductDownloadView.as_view(), name="download"),
    path('<slug>/download/', ProductDownloadView.as_view(), name="download_slug"),
    path('<int:pk>/edit/', ProductUpdateView.as_view(), name="update"),
    path('<slug>/edit/', ProductUpdateView.as_view(), name="update_slug"),
    path('ajax/rating/', ProductRatingAjaxView.as_view(), name="ajax_rating"),


]

src/tags/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    TagDetailView,
    TagListView
)

urlpatterns = [
    path('', TagListView.as_view(), name="list"),
    path('<slug>/', TagDetailView.as_view(), name="detail"),

]

src/billing/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from products.models import Product

class Transaction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=9.99, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    success = models.BooleanField(default=True)
    # transaction_id_payment_system = Braintree / Stripe
    # payment_method
    # last_four

    def __str__(self):
        return str(self.id)

src/products/models.py
import os
from django.core.files import File
import random
from PIL import Image
import shutil
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
from sellers.models import SellerAccount

def download_media_location(instance, filename):
    return "%s/%s" % (instance.slug, filename)

class Product(models.Model):
    seller = models.ForeignKey(SellerAccount, on_delete=models.CASCADE)
    #user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='managers_product', blank=True)
    media = models.ImageField(blank=True,
            null=True,
            upload_to=download_media_location,
            storage=FileSystemStorage(location=settings.PROTECTED_ROOT))
    title = models.CharField(max_length=150)
    slug = models.SlugField(blank=True,  unique=True)
    description = models.TextField(max_length=200, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=9.99, null=True)
    sale_active =models.BooleanField(default=False)
    sale_price = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        view_name = "products:detail_slug"
        return reverse(view_name, kwargs={"slug": self.slug})

    def get_edit_url(self):
        view_name = "sellers:product_edit"
        return reverse(view_name, kwargs={"pk": self.id})

    def get_download(self):
        view_name = "products:download_slug"
        url = reverse(view_name, kwargs={"slug": self.slug})
        return url

    @property
    def get_price(self):
        if self.sale_price and self.sale_active:
            return self.sale_price
        return self.price

    def get_html_price(self):
        price = self.get_price
        if price == self.sale_price:
            return "<p><span>%s</span> <span style='color:red;text-decoration:line-through;'>%s</span></p>" %(self.sale_price, self.price)
        else:
            return "<p>%s</p>" %(self.price)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['title']


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug

    qs = Product.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%ss-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug)
    return slug


def product_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_reciever, sender=Product)


def thumbnail_location(instance, filename):
    return "%s/%s" % (instance.product.slug, filename)


THUMB_CHOICES = (
    ("hd", "HD"),
    ("sd", "SD"),
    ("micro", "Micro"),
)


class Thumbnail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    type = models.CharField(max_length=20, choices=THUMB_CHOICES, default='hd')
    height = models.CharField(max_length=20, null=True, blank=True)
    width = models.CharField(max_length=20, null=True, blank=True)
    media = models.ImageField(
        width_field="width",
        height_field="height",
        blank=True,
        null=True,
        upload_to=thumbnail_location)

    def __str__(self):
        return str(self.media.path)

        class Meta:
            verbose_name = 'Thumbnail'
            verbose_name_plural = 'Thumbnails'


def create_new_thumb(media_path, instance, owner_slug, max_length, max_width):
        filename = os.path.basename(media_path)
        thumb = Image.open(media_path)
        size = (max_length, max_width)
        thumb.thumbnail(size, Image.ANTIALIAS)
        temp_loc = "%s/%s/tmp" % (settings.MEDIA_ROOT, owner_slug)
        if not os.path.exists(temp_loc):
            os.makedirs(temp_loc)
        temp_file_path = os.path.join(temp_loc, filename)
        if os.path.exists(temp_file_path):
            temp_path = os.path.join(temp_loc, "%s" % (random.random()))
            os.makedirs(temp_path)
            temp_file_path = os.path.join(temp_path, filename)

        temp_image = open(temp_file_path, "w")
        thumb.save(temp_image)
        thumb_data = open(temp_file_path, "rb")

        thumb_file = File(thumb_data)
        instance.media.save(filename, thumb_file)
        shutil.rmtree(temp_loc, ignore_errors=True)
        return True


def product_post_save_receiver(sender, instance, created, *args, **kwargs):
    if instance.media:
        hd, hd_created = Thumbnail.objects.get_or_create(product=instance, type='hd')
        sd, sd_created = Thumbnail.objects.get_or_create(product=instance, type='sd')
        micro, micro_created = Thumbnail.objects.get_or_create(product=instance, type='micro')

        hd_max = (500, 500)
        sd_max = (350, 350)
        micro_max = (150, 150)

        media_path = instance.media.path
        owner_slug = instance.slug

        if hd_created:
            create_new_thumb(media_path, hd, owner_slug, hd_max[0], hd_max[1])

        if sd_created:
            create_new_thumb(media_path, sd, owner_slug, sd_max[0], sd_max[1])

        if micro_created:
            create_new_thumb(media_path, micro, owner_slug, micro_max[0], micro_max[1])


post_save.connect(product_post_save_receiver, sender=Product)

class MyProducts(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return "%s" %(self.products.count())

    class Meta:
        verbose_name = 'My Product'
        verbose_name_plural = 'My Products'

class ProductRating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    rating = models.IntegerField(null=True, blank=True)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return "%s" %(self.rating)

    class Meta:
        verbose_name = 'Product Rating'
        verbose_name_plural = 'Products Ratings'

class CuratedProducts(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    section_name = models.CharField(max_length=20, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.section_name

    class Meta:
        verbose_name = 'Curated Product'
        verbose_name_plural = 'Curated Products'

src/products/forms.py
from django import forms
from .models import Product

from django.utils.text import slugify

PUBLISH_CHOISES = (
    #('', ""),
    ('publish', "Publish"),
    ('draft', "Draft"),
)

class ProductModelForm(forms.ModelForm):
    tags = forms.CharField(label='Related tags', required=False)
    publish = forms.ChoiceField(widget=forms.RadioSelect,choices=PUBLISH_CHOISES, required=False)
    # title = forms.CharField(label='Your Title', widget=forms.TextInput(
    #     attrs={
    #         "class":"custom-class",
    #         "placeholder":"Title",
    #     }
    # ))
    description = forms.CharField(widget=forms.Textarea(
        attrs={
            "class":"my-custom-class",
            "placeholder":"Description",
            "some-attr":"this"
        }
    ))
    price = forms.DecimalField()

    class Meta:
        model = Product
        fields = [
            "title",
            "description",
            "price",
            "media"
        ]

    def clean(self, *args, **kwargs):
        cleaned_data = super(ProductModelForm, self).clean(*args, **kwargs)
        #title = cleaned_data.get("title")
        # slug = slugify(title)
        # qs = Product.objects.filter(slug=slug).exists()
        # if qs:
        #     raise forms.ValidationError("Title is taken, new title is needed. Please try again")
        return cleaned_data

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price <= 1.00:
            raise forms.ValidationError("Price must be greater than $1,00")
        elif price >= 100.00:
            raise forms.ValidationError("Price must be less than $100,00")
        else:
            return price

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if len(title) > 3:
            return title
        else:
            raise forms.ValidationError("Title must be greater than 3 characteers long.")

src/templates/products/library_list.html
{% extends "base.html" %}
{% load get_thumbnail %}

{% block style %}

{% endblock style %}


{% block content %}
<h1>Library</h1>
<p>
<form method="GET" action="">
<input type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'>
<input type='submit' value='Search'/>
</form>
</p>


<table class='table'>
<thead>
	<th>Product</th>
	<th>Image</th>
	<th></th>
</thead>

{% for instance in product_list %}
<tr>
<td>
<a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a>
</td>

<td>
{% if instance|get_thumbnail:"micro" %}
	<a href='{{ instance.get_absolute_url }}'>

		<img src='{{ instance|get_thumbnail:"micro" }}' /></a>
        <br/>
	{% endif %}

</td>

<td>
	{% if instance.get_download %}
	<a href='{{ instance.get_download }}'>Download</a>
	{% else %}
	<span>Coming Soon</span>
	{% endif %}
	</td>
  </tr>
{% empty %}
    <li>No products in library yet, please shop now.</li>


{% endfor %}


	</table>


{% endblock %}

src/templates/products/product_detail.html
{% extends "base.html" %}

<style>
{% block style %}

.rating {
    float:left;
    width: 200px
}

/* :not(:checked) is a filter, so that browsers that don’t support :checked don’t
   follow these rules. Every browser that supports :checked also supports :not(), so
   it doesn’t make the test unnecessarily selective */
.rating:not(:checked) > input {
    position:absolute;
    top:-9999px;
    clip:rect(0,0,0,0);
}

.rating:not(:checked) > label {
    float:right;
    width:1em;
    padding:0 .1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:200%;
    line-height:1.2;
    color:#ddd;
    text-shadow:1px 1px #bbb, 2px 2px #666, .1em .1em .2em rgba(0,0,0,.5);
}

.rating:not(:checked) > label:before {
    content: '★ ';
}

.rating > input:checked ~ label {
    color: #f70;
    text-shadow:1px 1px #c60, 2px 2px #940, .1em .1em .2em rgba(0,0,0,.5);
}

.rating:not(:checked) > label:hover,
.rating:not(:checked) > label:hover ~ label {
    color: gold;
    text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
}

.rating > input:checked + label:hover,
.rating > input:checked + label:hover ~ label,
.rating > input:checked ~ label:hover,
.rating > input:checked ~ label:hover ~ label,
.rating > label:hover ~ input:checked ~ label {
    color: #ea0;
    text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
}

.rating > label:active {
    position:relative;
    top:2px;
    left:2px;
}

{% endblock style %}
</style>

<script>
$(document).ready(function(){
{% block jquery %}
$(".rating input[value='{{ my_rating }}']").attr("checked","checked");

$(".rating input[type='radio']").click(function(){
	var inputValue = $(this).val()
	console.log(inputValue)
	var request = $.ajax({
		method: "POST",
		url: "{% url 'products:ajax_rating' %}",
		data: {
			product_id: "{{ object.id }}",
			rating_value: inputValue,

		}
	})
	request.done(function(data){

	})

    request.fail(function(jqXHR, textStatus){
        if (jqXHR.status == 404){
            alert("Page not found!")
        } else if (jqXHR.status == 401){
            alert("You must be logged in to do this.")
        } else {
            alert("There was an error with your request. Please try again")
        }
    })
})


$('#purchase-btn').click(function(event) {
    event.preventDefault()
    var purchaseBtn = $(this)
    $('#dialog-confirm').fadeIn('300')
    $('#dialog-confirm').dialog({
        resizable: false,
        height: 350,
        width: 350,
        modal: true,
        buttons: {
            1: {
                id: "close",
                text: "Confirm",
                click: function(){
                    console.log("confirm")
                    var request = $.ajax({
                        method: "POST",
                        url: "{% url 'checkout' %}",
                        data: {
                            product_id: "{{ object.id }}",
                        }
                    })
                    request.done(function(data){
                        console.log(data.download)
                        console.log(data.preview)
                        purchaseBtn.before("<p><a href='" + data.download + "'>Download</p><a href ='" + data.preview + "'>Preview</p>")
                        purchaseBtn.fadeOut(500)

                        //console.log("working...")
                        // if (data.works) {
                        //     $("#content").html(data.time)
                        // }
                    })

                    request.fail(function(jqXHR, textStatus){
                        if (jqXHR.status == 404){
                            alert("Page not found!")
                        } else if (jqXHR.status == 403){
                            alert("You must be logged in to do this.")
                        } else {
                            alert("There was an error with your request. Please try again")
                        }
                    })

                    $(this).dialog("close")
                },
                class: "buy-btn"
            },
            2: {
                id: "close",
                text: "Cancel",
                click: function(){
                    $(this).dialog("close")
                },
                class: "cancel-btn"
            }
        }
    })
})
{% endblock jquery %}
})
</script>

{% block content %}

<div class='col-primary pull-left'>
    <h1>Product: {{  object.title }} <small>by: <a href='{{ object.seller.get_absolute_url }}'>{{ object.seller.user.username }}</a></small></h1>
    <p>{{ object.description }}</p>
    <p>{{ object.get_html_price|safe }}</p>
    <p> Purchases: {{ object.transaction_set.count }}</p>
    {% for img in object.thumbnail_set.all %}
    <img src="{{ img.media.url }}" />

    {% endfor %}
</div>


<div class='col-sidebar pull-right'>
    {% if request.user.is_authenticated and object in request.user.myproducts.products.all %}
    {% if object.media %}
        <p><a href='{{ object.get_download }}'>Download</a></p>
        <p><a href='{{ object.get_download }}?preview=True'>Preview</a></p>
        {% else %}
        <p>Product is coming soon for download</p>
    {% endif %}

    {% else %}
    <p><a id='purchase-btn' href="#">{% if object.media %}Purchase{% else %}Pre-Order{% endif %}</a></p>
    <div id='dialog-confirm' title='Confirm Purchase' style='display:none'>
        <p>Your card on file will be charged after you agree below.</p>
    </div>

    {% endif %}

    <p>
        <strong>My Rating</strong>
        <div class="rating">
            <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
            <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
            <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Meh">3 stars</label>
            <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
            <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Sucks big time">1 star</label>
        </divv>
        <br/>
        <p>
            {{ rating_avg.rating__avg }} Average Rating by {{ rating_avg.rating__count }} Users.
        </p>
    </p>


</div>

{{ block.super}}

<div class='clearfix'></div>

{% endblock %}

src/templates/products/product_list.html
{% extends "base.html" %}


{% block content %}
<h1>{% if vendor_name %}{{ vendor_name }}{% endif %} Products</h1>
<p>
<form method"GET" action="">
<input type='text' name='q' placeholder='Search' value=' {{ request.Get.q }}'>
<input type='submit' value='Search'/>
</form>
</p>
<ul>

{% include "products/product_list_snippet.html" with product_list=object_list %}

{% endblock %}

src/templates/products/product_list_snippet.html
{% load get_thumbnail %}

{% for instance in product_list %}
  <li class="">
      <a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></br>
      {% if instance|get_thumbnail:"micro" %}
      <a href='{{ instance.get_absolute_url }}'>
          <img src='{{ instance|get_thumbnail:"micro" }}' />
      </a></br>
      {% endif %}

      {{ instance.get_html_price|safe }}
  </li>
{% empty %}
  <li> No Products yet.</li>
{% endfor %}