src/digitalmarket/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView
from products.views import UserLibraryListView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('test/', CheckoutTestView.as_view(), name='test'),
    path('checkout/', CheckoutAjaxView.as_view(), name='checkout'),
    path('admin/', admin.site.urls),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('seller/', include(('sellers.urls', 'sellers'), namespace='sellers')),
    path('tags/', include(('tags.urls', 'tags'), namespace='tags')),
    path('library/', UserLibraryListView.as_view(), name='library'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sellers/urls.py
from django.contrib import admin
from django.urls import path, include

from products.views import (
        ProductUpdateView,
        ProductCreateView,
        SellerProductListView
)

from .views import (
        SellerDashboard,
        SellerTransactionListView,
        SellerProductDetailRedirectView
)

urlpatterns = [
    path('', SellerDashboard.as_view(), name="dashboard"),
    path('transactions/', SellerTransactionListView.as_view(), name="transactions"),
    path('products/', SellerProductListView.as_view(), name="product_list"),#sellers:product_list
    path('products/<int:pk>/', SellerProductDetailRedirectView.as_view()),
    path('products/<int:pk>/edit/', ProductUpdateView.as_view(), name="product_edit"),
    path('products/add/', ProductCreateView.as_view(), name="product_create"),
]

src/tags/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    TagDetailView,
    TagListView
)

urlpatterns = [
    path('', TagListView.as_view(), name="list"),
    path('<slug>/', TagDetailView.as_view(), name="detail"),

]

src/billing/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from products.models import Product

class Transaction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=9.99, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    success = models.BooleanField(default=True)
    # transaction_id_payment_system = Braintree / Stripe
    # payment_method
    # last_four

    def __str__(self):
        return str(self.id)

src/sellers/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.

class SellerAccount(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='manager_sellers', blank=True)
    active = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("products:vendor_detail", kwargs={"vendor_name": self.user.username})

    class Meta:
        verbose_name = 'Seller Account'
        verbose_name_plural = 'Sellers Accounts'

src/sellers/forms.py
from django import forms

class NewSellerForm(forms.Form):
    agree = forms.BooleanField(label='Agree to Terms', widget=forms.CheckboxInput)

src/dashboard/views.py
import random

from django.views.generic import View
from django.shortcuts import render

# Create your views here.

from products.models import Product, CuratedProducts

class DashboardView(View):
	def get(self, request, *args, **kwargs):
		tag_views = None
		products = None
		top_tags = None
		curated = CuratedProducts.objects.filter(active=True).order_by("?")
		try:
			tag_views = request.user.tagview_set.all().order_by("-count")[:5]
		except:
			pass

		owned = None

		try:
			owned = request.user.myproducts.products.all()
		except:
			pass

		if tag_views:
			top_tags = [x.tag for x in tag_views]
			products = Product.objects.filter(tag__in=top_tags)
			if owned:
				products = products.exclude(pk__in=owned)

			if products.count() < 10:
				products = Product.objects.all().order_by("?")
				if owned:
					products = products.exclude(pk__in=owned)
				products = products[:10]
			else:
				products = products.distinct()
				products = sorted(products, key= lambda x: random.random())

		context = {
			"products": products,
			"top_tags": top_tags,
			"curated": curated
		}
		return render(request, "dashboard/view.html", context)

src/sellers/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView

# Create your views here.
from billing.models import Transaction
from products.models import Product
from digitalmarket.mixins import LoginRequiredMixin

from .models import SellerAccount
from .mixins import SellerAccountMixin
from .forms import NewSellerForm

from django.views.generic.base import RedirectView
from django.shortcuts import get_object_or_404

class SellerProductDetailRedirectView(RedirectView):
    permanent = True
    def get_redirect_url(self, *args, **kwargs):
        obj = get_object_or_404(Product, pk=kwargs['pk'])
        return obj.get_absolute_url()

class SellerTransactionListView(SellerAccountMixin, ListView):
    model = Transaction
    template_name ="sellers/transaction_list_view.html"

    def get_queryset(self):
        return self.get_transactions()

class SellerDashboard(SellerAccountMixin, FormMixin, View):
    form_class = NewSellerForm
    success_url = "/seller/"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        apply_form = self.get_form() #NewSellerForm()
        account = self.get_account()
        exists = account
        active = None

        if exists:
            active = account.active

        context = {}

        #if the account doesn´t exists, show form
        #if exists and not active, show pending
        #if exists and active show dashboard data

        if not exists and not active:
            context["title"] = "Apply for Account"
            context["apply_form"] = apply_form
        elif exists and not active:
            context["title"] = "Account Pending"
        elif exists and active:
            context["title"] = "Seller Dashboard"
            #products = Product.objects.filter(seller=account)
            context["products"] = self.get_products()
            transactions_today = self.get_transactions_today()
            context["transactions_today"] = transactions_today
            context["today_sales"] = self.get_today_sales()
            context["total_sales"] = self.get_total_sales()
            context["transactions"] = self.get_transactions().exclude(pk__in=transactions_today)[:6]
        else:
            pass

        return render(request, "sellers/dashboard.html", context)

    def form_valid(self, form):
        valid_data = super(SellerDashboard, self).form_valid(form)
        obj = SellerAccount.objects.create(user=self.request.user)
        return valid_data

src/templates/sellers/dashboard.html
{% extends "base.html" %}

{% block content %}
<h1> {{ title }}</h1>

{% if apply_form %}

<form method="POST" action=''> {% csrf_token %}
    <h3> Rules of the Marketplace </h3>
    <ol>
        <li>
            Be kind
        </li>
        <li>
            Be nice
        </li>
        <li>
            Be smart
        </li>
    </ol>
{{ apply_form.as_p }}
<br/>
<input type='submit'/>
</form>

{% endif %}

{% if products %}
<div class='pull-right col-sidebar'>
    <h4>My Products <br/> <small><a href='{% url "sellers:product_create"%}'>Add</a> | <a href='{% url "sellers:product_list"%}'>View All</a></small></h4>
{% include "products/product_list_snippet.html" with product_list=products %}
</div>
{% endif %}


{% if transactions %}
<div class='pull-left col-primary'>
<h3>Today's sales are ${{ today_sales }}</h3>
{% include "sellers/transaction_list.html" with transaction_list=transactions_today %}

<br/>
    <h3>Recent Transaction History (Total Sales: ${{ total_sales }})</h3>
{% include "sellers/transaction_list.html" with transaction_list=transactions %}

<p>
<a href='{% url "sellers:transactions" %}'>View all transactions</a>
</p>

</div>
{% endif %}


{% endblock %}

src/templates/sellers/product_list_view.html
{% extends "base.html" %}
{% load get_thumbnail %}

{% block content %}
<h1>My Seller Products</h1>
<p>
<form method"GET" action="">
<input type='text' name='q' placeholder='Search' value=' {{ request.Get.q }}'>
<input type='submit' value='Search'/>
</form>
</p>
<table>

    {% for instance in product_list %}
      <tr class="">
          <td>{{ instance.id }}
          </td>
          <td>
              <a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a>
          </td>
          <td>
          {% if instance|get_thumbnail:"micro" %}
          <a href='{{ instance.get_absolute_url }}'>
              <img src='{{ instance|get_thumbnail:"micro" }}' style='max-width:100px' />
          </a></br>

          {% endif %}
          </td>
          <td>{{ instance.price }}
          </td>
          </td>
          <td><a href='{{ instance.get_edit_url }}'>Edit</a> | <a href='#'>Delete</a>
          </td>
      </li>
    {% empty %}
      <li> No Products yet.</li>
    {% endfor %}

</table>

{% endblock %}

src/templates/sellers/transaction_list.html
<table>

<thead>

<th>Product</th>
<th>User</th>
<th>Sale Total</th>
	<th></th>
</thead>
<tbody>
{% for trans in transaction_list %}
<tr>
	<td>{{ trans.product }}</td>
	<td>{{ trans.user }}</td>
	<td>{{ trans.price }}</td>
	<td>{{ trans.timestamp|timesince }} ago</td>
</tr>
{% endfor %}
</tbody>
</table>

src/templates/sellers/transaction_list_view.html
{% extends "base.html" %}


{% block content %}
<h1>Transaction</h1>

    {% include "sellers/transaction_list.html" with transaction_list=object_list %}

{% endblock %}